{application,project4,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"project4"},
              {modules,['Elixir.DB','Elixir.Master','Elixir.Misc',
                        'Elixir.Project4','Elixir.QueryDB',
                        'Elixir.User_Profiles','Elixir.Worker']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
