{application,project4,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"project4"},
              {modules,['Elixir.Client','Elixir.LoadBalancer','Elixir.Master',
                        'Elixir.Misc','Elixir.MsgDB','Elixir.Project4',
                        'Elixir.User_Profiles','Elixir.Worker']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
